services:
  postgres:
    image: postgres:16-alpine
    container_name: mdm-postgres
    environment:
      POSTGRES_USER: mdm
      POSTGRES_PASSWORD: mdm
      POSTGRES_DB: mdm
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mdm -d mdm"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [mdmnet]

  kafka:
    image: apache/kafka:4.0.1
    container_name: mdm-kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://host.docker.internal:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9094:9094"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks: [mdmnet]

volumes:
  db-data: {}
  kafka-data: {}

networks:
  mdmnet: {}
